name: Lint
on:
  push:
env:
  PIPENV_VENV_IN_PROJECT: enabled
jobs:
  check-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install pipenv
      run: python -m pip install --upgrade pipenv wheel

    - name: Install dependencies
      run: pipenv install pylint

    - name: Check code
      run: pipenv run pylint --rcfile=.pylintrc **/*.py
